### PR TITLE
Feature/fedora21

### LINKED ISSUE #36: yum repo setup fails on fedora 21
Note that the name of the package attempting to be retried is `puppetlabs-release-21-.noarch.rpm` while it should be `puppetlabs-release-21-11.noarch.rpm`

```
13:47:51 +0000 INFO: Version parameter defined: 3.7.4
13:47:51 +0000 INFO: Downloading Puppet 3.7.4 for fedora...
13:47:51 +0000 INFO: Fedora platform! Lets get the RPM...
13:47:51 +0000 INFO: Downloading http://yum.puppetlabs.com/fedora/f21/products/x86_64/puppetlabs-release-21-.noarch.rpm
13:47:51 +0000 INFO:   to file /tmp/install.sh.2258.23727/puppetlabs-release-21-.noarch.rpm
13:47:51 +0000 INFO: Trying wget...
13:47:51 +0000 CRIT: ERROR 404
```

### PR DESCRIPTION
**Pull request by jhoblitt**
Fixes #36

### CODE REVIEW

**Comment by jhoblitt** [comment]
@petems ping?

**Comment by petems** [comment]
@jhoblitt Awesome, thanks! Let me run the Vagrant check then I'll merge :+1:

**Comment by jhoblitt** [comment]
\o/

**Comment by petems** [comment]
Worked like a charm! But I should probably detect when fedora version is nil too, I'll open an issue for that :+1:

**Comment by jhoblitt** [comment]
@petems I owe you a pint!

**Pull request merged**
