### PR TITLE
Addition of Puppet 6 Changes

### PR DESCRIPTION
**Pull request by ppouliot**
Pull request to add script and Vagrantfile changes to support puppet6

### CODE REVIEW

**Comment by ppouliot** [comment]
Tests have passed, any chance to merge this?

**Comment by craigwatson** [comment]
@petems would be great to get this merged, I use the install-shell for my modules' Vagrantfiles, and I'm currently not able to test Puppet6 :(

**Comment by petems** [comment]
I apologize everyone! 

I unwatched all repos accidentally mid-last year, and forgot to re-follow those under my namespace again 😓 

This looks good, I'll merge! 😄

**Comment by craigwatson** [comment]
Awesome, thanks @petems - I think #118 can also be closed as a duplicate of this :)

**Pull request merged**
